### ISSUE TITLE
How to attach pulley to wheels?

### ISSUE THREAD

**Issue by kssummer** [XRobots/ReallyUsefulRobot#15]
How are you attaching the t5 wheel pulley to the wheel? There doesn't seem to be any mounting holes for screwing them on. Are you gluing them?
I've printed them, but the pulley just spins around the wheel. Either my tolerance is off, or there's something I'm missing.

**Comment by XRobots** [comment]
Yep glue

**Comment by kssummer** [comment]
Thanks James. Love your videos.
