### ISSUE TITLE
How to attach tires to wheel?

### ISSUE THREAD

**Issue by kssummer** [XRobots/ReallyUsefulRobot#16]
Does anyone have any tips on how to attach the TPU tires to the wheel? I can't tell if the tolerance is off, or if I'm just weak, but I cannot get the tires around the wheel.

**Comment by XRobots** [comment]
I used standard Ninjaflex which is fairly soft. Pretty sure I still had to stand on the hubs to push them in though.

**Comment by kssummer** [comment]
Thanks. I ended up putting the tires in hot water and chilling the hub in the freezer. The tire got soft enough to pull over the hub.
(for the record, I used Overture TPU)
