### ISSUE TITLE
Mounting hole diameters

### ISSUE THREAD

**Issue by tom-f-oconnell** [XRobots/ReallyUsefulRobot#3]
I noticed a few holes in the assembly where two parts are joined by a screw have the same inner diameter for the portion the screw should pass through (the clearance portion) as well as the part the screw should be threaded in to. Is this actually how it's printed? I might expect the inner diameter of the part the screw should thread in to to be slightly smaller or something, either to tap the hole or so a screw can self-thread.  Or I might expect the holes-for-threads to be somewhat wider than the clearance holes to accept a heat set insert or something.

Two specific cases I'm looking at now:
- between the 4 walls of the body and each of the plates that connects the pairs of walls together
- between the two halves of the Jetson mount
...there might also be others I'm not seeing right now, but I assume the answer is the same everywhere.

What kinds of fasteners do you use in these cases? Just a screw (self-tapping?), some kind of thread insert, or something else?

Thanks!

**Comment by XRobots** [comment]
Sometimes I take a 3mm drill to the one that should be larger. I'm using 2.9mm self tapping countersunk screws.
