### ISSUE TITLE
Consolidated BOM

### ISSUE THREAD

**Issue by tom-f-oconnell** [XRobots/ReallyUsefulRobot#4]
Do you think it'd be possible to add a consolidated BOM somewhere? Most of the large non-printed parts, like the major electronic components, are mentioned in the README or in the videos, but there are still some things I'm not sure what / where to buy, such as:
- the springs for the base suspension
- the casters
- the vertical timing belt (and maybe some other components to the vertical drive that I missed)
- fasteners (I know use use 2.9mm self tapping threads in a few places, but it seems there's at least one other kind of fastener)
- the bearings (though I could probably figure this out at least)

I know it might be a bit tedious, especially with the fasteners, but I think it'd be a big help to people trying to recreate this project.

If you want to send me a CSV / spreadsheet / Google Sheet link, I can also help format the BOM as a Github Markdown table if you'd like, perhaps in the README.

Thanks!

**Comment by XRobots** [comment]
I've added the vertical belt details to the readme.

The springs I have are actually too tight - they were just some springs I bought off eBay, so you'd be better trying some experimentation here.

The casters are some 50mm ones I had in my spares box, the CAD shows placeholders for the envelope so again, you'd need to see what you can find locally and potentially modify the design to the height correct.

There are a few M4 socket cap bolts in it, but that's about it?

Wheel bearing sizes are shown in the CAD.
